import 'dart:convert';
import 'dart:io';

import 'package:analyzer/file_system/physical_file_system.dart';
import 'package:good_intentions/good_intentions.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('e2e scenarios', () {
    test('validates normal multi-package directory and writes PlantUML', () {
      final scenario = _E2eScenario.normal();
      return _runScenario(scenario);
    });

    test('validates workspace package and writes PlantUML', () {
      final scenario = _E2eScenario.workspace();
      return _runScenario(scenario);
    });
  });
}

Future<void> _runScenario(_E2eScenario scenario) async {
  scenario.prepare();
  addTearDown(scenario.cleanUp);

  final loggerOutput = StringBuffer();
  final validator = ArchitectureValidator.withDefaults(
    resourceProvider: PhysicalResourceProvider.INSTANCE,
  );

  await expectLater(
    validator.validatePackage(
      packageRoot: scenario.appRoot,
      packageName: 'app',
      logger: Logger(loggerOutput),
    ),
    completes,
  );

  expect(loggerOutput.toString(), contains('Architecture OK.'));

  final pumlFile = File(p.join(scenario.appRoot, 'lib', 'architecture.g.puml'));
  expect(pumlFile.existsSync(), isTrue);

  final puml = pumlFile.readAsStringSync();
  expect(puml, contains('package "app"'));
  expect(puml, contains('class AppUseCase << useCase >>'));
  expect(puml, contains('class AppRepository << repository >>'));
  expect(puml, contains('class SharedApi << dataSource >>'));
  expect(puml, contains('AppUseCase --> AppRepository'));
  expect(puml, contains('AppRepository --> SharedApi'));
}

class _E2eScenario {
  _E2eScenario._({
    required this.scenarioRoot,
    required this.packageConfigRoot,
  }) : appRoot = p.join(scenarioRoot, 'app'),
       sharedRoot = p.join(scenarioRoot, 'shared');

  factory _E2eScenario.normal() {
    final root = p.join(_packageRoot, 'e2e_scenario');
    return _E2eScenario._(
      scenarioRoot: root,
      packageConfigRoot: p.join(root, 'app'),
    );
  }

  factory _E2eScenario.workspace() {
    final root = p.join(_packageRoot, 'e2e_scenario_workspace');
    return _E2eScenario._(
      scenarioRoot: root,
      packageConfigRoot: root,
    );
  }

  final String scenarioRoot;
  final String packageConfigRoot;
  final String appRoot;
  final String sharedRoot;

  void prepare() {
    cleanUp();

    final dartTool = Directory(p.join(packageConfigRoot, '.dart_tool'))
      ..createSync(recursive: true);
    File(p.join(dartTool.path, 'package_config.json')).writeAsStringSync(
      const JsonEncoder.withIndent('  ').convert({
        'configVersion': 2,
        'packages': [
          {
            'name': 'app',
            'rootUri': Uri.directory(appRoot).toString(),
            'packageUri': 'lib/',
            'languageVersion': '3.11',
          },
          {
            'name': 'shared',
            'rootUri': Uri.directory(sharedRoot).toString(),
            'packageUri': 'lib/',
            'languageVersion': '3.11',
          },
          {
            'name': 'intentions',
            'rootUri': Uri.directory(_intentionsRoot).toString(),
            'packageUri': 'lib/',
            'languageVersion': '3.11',
          },
        ],
      }),
    );

    File(p.join(packageConfigRoot, 'pubspec.lock')).writeAsStringSync(
      '# Generated by e2e_scenarios_test.dart\n',
    );
  }

  void cleanUp() {
    final dartTool = Directory(p.join(packageConfigRoot, '.dart_tool'));
    if (dartTool.existsSync()) {
      dartTool.deleteSync(recursive: true);
    }

    final lockFile = File(p.join(packageConfigRoot, 'pubspec.lock'));
    if (lockFile.existsSync()) {
      lockFile.deleteSync();
    }

    final pumlFile = File(p.join(appRoot, 'lib', 'architecture.g.puml'));
    if (pumlFile.existsSync()) {
      pumlFile.deleteSync();
    }
  }
}

final String _packageRoot = Directory.current.path;
final String _repoRoot = p.dirname(_packageRoot);
final String _intentionsRoot = p.join(_repoRoot, 'intentions');
